# Generated by Django 4.1 on 2022-08-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamId', models.IntegerField(max_length=12, unique=True)),
                ('nameTeams', models.CharField(blank=True, max_length=250)),
                ('seraial', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.CharField(blank=True, max_length=60, null=True)),
                ('isFavorite', models.BooleanField(verbose_name='favorito')),
            ],
            options={
                'verbose_name': 'favorite',
                'verbose_name_plural': 'favorites',
                'db_table': 'favorite',
                'ordering': ['id'],
            },
        ),
    ]
