# Generated by Django 4.1 on 2022-08-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='teamId',
            field=models.IntegerField(unique=True),
        ),
    ]
